---
apiVersion: v1
kind: Namespace
metadata:
  name: triage
  labels:
    name: triage
    app: triage-platform
---
# ConfigMap for shared configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: triage-config
  namespace: triage
data:
  # Database configuration
  POSTGRES_DB: "triage"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  
  # OpenSearch configuration
  OPENSEARCH_HOST: "opensearch-service"
  OPENSEARCH_PORT: "9200"
  
  # Neo4j configuration
  NEO4J_HOST: "neo4j-service"
  NEO4J_PORT: "7687"
  NEO4J_HTTP_PORT: "7474"
  
  # Application configuration
  RUST_LOG: "info"
  SERVER_PORT: "3001"
  CLIENT_PORT: "3000"
  
  # OAuth redirect URIs (adjust for your domain)
  GOOGLE_REDIRECT_URI: "http://localhost:3000/auth/google/callback"
  SLACK_REDIRECT_URI: "http://localhost:3000/auth/slack/callback"
---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: triage-secrets
  namespace: triage
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "triage_user"
  POSTGRES_PASSWORD: "secure_password_change_me"
  
  # Neo4j credentials
  NEO4J_AUTH: "neo4j/secure_neo4j_password_change_me"
  
  # OAuth secrets (you'll need to provide these)
  GOOGLE_CLIENT_ID: "your_google_client_id"
  GOOGLE_CLIENT_SECRET: "your_google_client_secret"
  SLACK_CLIENT_ID: "your_slack_client_id"
  SLACK_CLIENT_SECRET: "your_slack_client_secret"
  
  # OpenSearch admin password
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "secure_opensearch_password_change_me"