CREATE TABLE IF NOT EXISTS issues (
    id TEXT PRIMARY KEY,
    key TEXT,
    self_link TEXT,
    summary TEXT,
    status TEXT,
    issue_type TEXT,
    issue_type_id TEXT,
    is_subtask BOOLEAN,
    hierarchy_level INTEGER,
    priority TEXT,
    priority_id TEXT,
    assignee TEXT,
    reporter TEXT,
    labels TEXT,
    -- JSON array as string
    created TEXT,
    updated TEXT,
    project_name TEXT,
    project_key TEXT,
    extracted_links TEXT,
    -- JSON array as string
    rendered_fields TEXT,
    names TEXT,
    schema TEXT,
    transitions TEXT,
    edit_meta TEXT,
    changelog TEXT,
    versioned_representations TEXT,
    watcher TEXT,
    attachment TEXT,
    sub_tasks TEXT,
    description TEXT,
    project TEXT,
    comment TEXT,
    issue_links TEXT,
    work_log TEXT,
    time_tracking TEXT
);